import turtle
##turtle.register_shape("shape1", ((50,0), (50,50), (0,50), (-50,25),(0,0)))
##turtle.shape("shape1")
turtle.register_shape("spiderman.gif")
turtle.shape("spiderman.gif")
##turtle.forward(500)
##turtle.color("Red")
##turtle.color("Blue")
##turtle.forward(500)
##turtle.left(145)
##turtle.color("Green")
##turtle.forward(500)
##turtle.left(145)
##turtle.color("Orange")
##turtle.forward(500)
for index in range(360):
	turtle.pendown()
	turtle.forward(200)
	turtle.right(45)
	turtle.forward(100)
	turtle.right(90)
	turtle.forward(50)
	turtle.penup()
	turtle.goto(0,0)
	turtle.right(64)

turtle.mainloop()